---

- name: Network Getting Started First Playbook
  connection: network_cli
  hosts: firewall1
  gather_facts: no
  tasks:
  
    - name: config change 
      asa_config:
        backup: yes
        
