#!/bin/bash

#Juniper Core Firewall1 ########################################################################
Juniper_Core_Firewall1_NEW=$(ls -l Juniper_Core_Firewall1_config.* 2>/dev/null | awk '{ print $9 }'| sed -n 1p)
Juniper_Core_Firewall1_OLD=$(ls -l Juniper_Core_Firewall1_config.* 2>/dev/null | awk '{ print $9 }'| sed -n 2p)


diff -q $Juniper_Core_Firewall1_NEW $Juniper_Core_Firewall1_OLD 1>/dev/null 2>/dev/null
if [[ $? == "0" ]]
then
  echo "The same deleting" $Juniper_Core_Firewall1_NEW
  rm $Juniper_Core_Firewall1_NEW
fi
##################################################################################################
#Juniper Core Firewall2########################################################################
Juniper_Core_Firewall2_NEW=$(ls -l Juniper_Core_Firewall2_config.* 2>/dev/null | awk '{ print $9 }'| sed -n 1p)
Juniper_Core_Firewall2_OLD=$(ls -l Juniper_Core_Firewall2_config.* 2>/dev/null | awk '{ print $9 }'| sed -n 2p)


diff -q $Juniper_Core_Firewall2_NEW $Juniper_Core_Firewall2_OLD 1>/dev/null 2>/dev/null
if [[ $? == "0" ]]
then
  echo "The same deleting" $Juniper_Core_Firewall2_NEW
  rm $Juniper_Core_Firewall2_NEW
fi
##################################################################################################
#Juniper Branch Firewall1########################################################################
Juniper_Branch_Firewall1_NEW=$(ls -l Juniper_Branch_Firewall1* 2>/dev/null | awk '{ print $9 }'| sed -n 1p )
Juniper_Branch_Firewall1_OLD=$(ls -l Juniper_Branch_Firewall1* 2>/dev/null | awk '{ print $9 }'| sed -n 2p )


diff -q $Juniper_Branch_Firewall1_NEW $Juniper_Branch_Firewall1_OLD 1>/dev/null 2>/dev/null
if [[ $? == "0" ]]
then
  echo "The same deleting" $Juniper_Branch_Firewall1_NEW
  rm $Juniper_Branch_Firewall1_NEW
fi
##################################################################################################

#Juniper Branch Firewall2########################################################################
Juniper_Branch_Firewall2_NEW=$(ls -l Juniper_Branch_Firewall2* 2>/dev/null | awk '{ print $9 }'| sed -n 1p)
Juniper_Branch_Firewall2_OLD=$(ls -l Juniper_Branch_Firewall2* 2>/dev/null | awk '{ print $9 }'| sed -n 2p)


diff -q $Juniper_Branch_Firewall2_NEW $Juniper_Branch_Firewall2_OLD 1>/dev/null 2>/dev/null
if [[ $? == "0" ]]
then
  echo "The same deleting" $Juniper_Branch_Firewall2_NEW
  rm $Juniper_Branch_Firewall2_NEW
fi
##################################################################################################

#Juniper Branch Firewall3
Juniper_Branch_Firewall3_NEW=$(ls -l Juniper_Branch_Firewall3* 2>/dev/null | awk '{ print $9 }'| sed -n 1p)
Juniper_Branch_Firewall3_OLD=$(ls -l Juniper_Branch_Firewall3* 2>/dev/null | awk '{ print $9 }'| sed -n 2p)


diff -q $Juniper_Branch_Firewall3_NEW $Juniper_Branch_Firewall3_OLD 1>/dev/null 2>/dev/null
if [[ $? == "0" ]]
then
  echo "The same deleting" $Juniper_Branch_Firewall3_NEW
  rm $Juniper_Branch_Firewall3_NEW
fi

##################################################################################################
#cisco firewall core########################################################################
cisco_core_firewall1_NEW=$(ls -lt cisco_core_firewall1* 2>/dev/null | awk '{ print $9 }'| sed -n 1p)
cisco_core_firewall1_OLD=$(ls -lt cisco_core_firewall1* 2>/dev/null | awk '{ print $9 }'| sed -n 2p)


diff -q $cisco_core_firewall1_NEW $cisco_core_firewall1_OLD 1>/dev/null 2>/dev/null
if [[ $? == "0" ]]
then
  echo "The same deleting" $cisco_core_firewall1_NEW 
  rm $cisco_core_firewall1_NEW 
fi

##################################################################################################
