---

- name: Juniper config backup playbook
  gather_facts: false
  hosts: junos
  connection: local
  tasks:
  
    - name: backing juniper config up
      junos_config:
        backup: yes
    
          
