---

- name: Network Getting Started First Playbook
  gather_facts: false
  hosts: junos
  connection: local
  tasks:
  
    - name: configurable backup path
      junos_config:
        backup: yes
    
          
